# Build using -> 
# docker build -t wasaphoto-backend:latest -f Dockerfile.backend .
#
# Execute the Dockerfile.backend using ->
# docker run -it -v /home/:/WASAPhoto/ -p 3000:3000 --rm wasaphoto-backend:latest

FROM golang:1.19.4 as backend_compiler
WORKDIR /GoFiles/
COPY . .
RUN go build -o /Executable/ ./cmd/webapi

FROM debian:stable
WORKDIR /executable_backend/
COPY --from=backend_compiler /Executable/ .
EXPOSE 3000
VOLUME ["/WASAPhoto/"]
CMD ["./webapi"]
