# Build using -> 
# docker build -t wasaphoto-frontend:latest -f Dockerfile.frontend .
#
# Execute the Dockerfile.frontend using ->
# docker run -it -p 8080:80 --rm wasaphoto-frontend:latest

FROM node:lts as frontend_compiler
WORKDIR /src/webui
COPY webui .
RUN npm run build-prod

FROM nginx:latest
COPY --from=frontend_compiler /src/webui/dist /usr/share/nginx/html
EXPOSE 80